export const INIT = 'INIT'

export const FETCH_SETS_REQUEST = 'FETCH_SETS_REQUEST'
export const FETCH_SETS_SUCCESS = 'FETCH_SETS_SUCCESS'
export const FETCH_SETS_FAILURE = 'FETCH_SETS_FAILURE'

export const FETCH_EPISODE_REQUEST = 'FETCH_EPISODE_REQUEST'
export const FETCH_EPISODE_SUCCESS = 'FETCH_EPISODE_SUCCESS'

export const FETCH_CONTENT_REQUEST = 'FETCH_CONTENT_REQUEST'
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS'

export const SELECTED_EPISODE = 'SELECTED_EPISODE'